# Generated by Django 5.1.2 on 2024-10-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("cost", models.PositiveIntegerField()),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("Универсал", "Универсал"),
                            ("Седан", "Седан"),
                            ("Купе", "Купе"),
                            ("Кабриолет", "Кабриолет"),
                        ],
                        max_length=50,
                    ),
                ),
                ("video", models.URLField()),
            ],
        ),
    ]
