# Generated by Django 5.1.2 on 2024-11-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Кабриолет', 'Кабриолет'), ('Купе', 'Купе'), ('Седан', 'Седан'), ('Универсал', 'Универсал')], max_length=50, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.PositiveIntegerField(help_text='Цену нужно писать в долларах', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='car',
            name='video',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.CreateModel(
            name='CommentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate', models.CharField(choices=[('**', '**'), ('*****', '*****'), ('***', '***'), ('*', '*'), ('****', '****')], max_length=17)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.car')),
            ],
        ),
    ]
