# Generated by Django 5.1.2 on 2024-11-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_options_alter_car_car_type_alter_car_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Кабриолет', 'Кабриолет'), ('Универсал', 'Универсал'), ('Купе', 'Купе'), ('Седан', 'Седан')], max_length=50, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='commentcar',
            name='rate',
            field=models.CharField(choices=[('*', '*'), ('*****', '*****'), ('**', '**'), ('****', '****'), ('***', '***')], max_length=17),
        ),
    ]
