# Generated by Django 5.1.2 on 2024-11-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_car_type_alter_commentcar_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Универсал', 'Универсал'), ('Кабриолет', 'Кабриолет'), ('Купе', 'Купе'), ('Седан', 'Седан')], max_length=50, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='commentcar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='car.car'),
        ),
        migrations.AlterField(
            model_name='commentcar',
            name='rate',
            field=models.CharField(choices=[('***', '***'), ('**', '**'), ('*', '*'), ('****', '****'), ('*****', '*****')], max_length=17),
        ),
    ]
