# Generated by Django 5.1.2 on 2024-11-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_car_type_alter_commentcar_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Купе', 'Купе'), ('Универсал', 'Универсал'), ('Кабриолет', 'Кабриолет'), ('Седан', 'Седан')], max_length=50, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название машины'),
        ),
    ]
