# Generated by Django 5.1.2 on 2024-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_car_type_alter_car_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Универсал', 'Универсал'), ('Кабриолет', 'Кабриолет'), ('Купе', 'Купе'), ('Седан', 'Седан')], max_length=50, verbose_name='Тип машины'),
        ),
    ]
