# Generated by Django 5.1.2 on 2024-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Универсал', 'Универсал'), ('Кабриолет', 'Кабриолет'), ('Седан', 'Седан'), ('Купе', 'Купе')], max_length=50, verbose_name='Тип машины'),
        ),
    ]
